

# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 85..100
  round: down
  precision: 6
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 1%

# Ignore test files and main.rs
ignore:
  - "tests"
  - "src/main.rs"  # <- This line ignores the main Rust file

# Make comments less noisy
comment:
  layout: "files"
  require_changes: true