[package]
name = "jsavrs"
version = "0.1.0"
edition = "2024"
authors = ["Giuseppe Bianconi(Giuseppe-Bianc) <bianconig6@gmail.com>"]
description = "Un transpiler scritto in Rust che utilizza Logos per il lexing."
license = "Apache-2.0"
repository = "https://github.com/Giuseppe-Bianc/jsavrs"
readme = "README.md"
keywords = ["rust", "logos", "lexer"]
categories = ["compilers", "parsing"]

[lib]
name = "jsavrs"
path = "src/lib.rs"

[[bin]]
name = "jsavrs"
path = "src/main.rs"

[dependencies]
logos = "0.15.0"
thiserror = "2.0.12"