[package]
name = "jsavrs"
version = "0.1.0"
edition = "2024"

[lib]
name = "jsavrs"
path = "src/lib.rs"

[[bin]]
name = "jsavrs"
path = "src/main.rs"

[dependencies]
logos = "0.15.0"
thiserror = "2.0.12"
