mod access_control;
mod basic_block;
mod cfg;
mod function;
pub mod generator;
mod instruction;
mod module;
mod scope;
mod scope_manager;
mod terminator;
mod types;
mod value;

pub use access_control::{AccessController, AccessRules, Operation};
pub use basic_block::BasicBlock;
pub use cfg::ControlFlowGraph;
pub use function::{Function, FunctionAttributes, IrParameter, ParamAttributes};
pub use instruction::{CastKind, Instruction, InstructionKind, IrBinaryOp, IrUnaryOp, VectorOp};
pub use module::{DataLayout, Module, TargetTriple};
pub use scope::Scope;
pub use scope_manager::ScopeManager;
pub use terminator::{Terminator, TerminatorKind};
pub use types::{IrType, ResourceId, ScopeId};
pub use value::{IrConstantValue, IrLiteralValue, Value, ValueDebugInfo, ValueKind};
