name: Coverage

on:
  push:
    branches: [ '*' ]   # Scatta su qualsiasi branch
    tags: [ '*' ]       # Scatta su qualsiasi tag
  pull_request:
    branches: [ '*' ]   # Scatta su PR verso qualsiasi branch

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, beta, nightly ]

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        run: rustup update ${{ matrix.toolchain }}
        shell: bash

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests and generate Cobertura XML
        run: cargo llvm-cov --all-features --workspace --cobertura --output-path coverage.xml
        env:
          INSTA_UPDATE: force  # Force update snapshots (use with caution!)

      # PULIZIA FILE TEMPORANEI PRIMA DELL'UPLOAD
      - name: Clean up temporary files
        run: |
          rm -f codecov* *.sig *.SHA256SUM
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.os }}-rust-${{ matrix.toolchain }}
          slug: Giuseppe-Bianc/jsavrs
          verbose: true
          disable_search: true  # DISABILITA RICERCA AUTOMATICA FILE
          fail_ci_if_error: true